CRUD/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('employee.urls')),
    url(r'^employee/index', include('employee.urls'))
]

employee/urls.py
from django.contrib import admin
from django.urls import path
from employee import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),
    path('show',views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]

employee/models.py
from django.db import models

class Employee(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.IntegerField()
    gender = models.CharField(max_length=100, default="", editable=True)
#   country = CountryField()
#  state = models.CharField(max_length=10, default="", editable=False)
    languages = models.CharField(max_length=10, default="", editable=True)
    eimage = models.ImageField()

    class Meta:
        db_table = "employee"

employee/forms.py
from django import forms
from employee.models import Employee

class EmployeeForm(forms.ModelForm):
    eid = forms.CharField(max_length=20, required=True)
    ename = forms.CharField(max_length=20, required=True)
    eemail = forms.EmailField( required=True)
    econtact = forms.IntegerField(required=True)
    gender = forms.CharField(max_length=20, required=True)
    #country = forms.CharField(max_length=25, required=True)
    #state = forms.CharField(max_length=20, required=True)
    languages = forms.CharField(max_length=20)
    #eimage = forms.FileField()




    class Meta:
        model = Employee
        fields = ("eid","ename","eemail","econtact","gender","languages","eimage")

    def save(self, commit=True):
        employee = super(EmployeeForm, self).save(commit=False)
        employee.eemail = self.cleaned_data['email']
        if commit:
            employee.save()
        return employee

employee/views.py
from django.shortcuts import render, redirect
from employee.forms import EmployeeForm
from employee.models import Employee
from django.contrib import messages

def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            employee = form.save()
            return redirect('employee/show.html')
        else:
            print("Form unsaved")


    else:
        form = EmployeeForm()
    return render(request, 'index.html', {'form':form})

def show(request):
    employees = Employee.objects.all()
    return render(request,"show.html",{'employees':employees})

def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request,'edit.html', {'employee':employee})

def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance = employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'employee': employee})

def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/show")

employee/templates/edit.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
     {% load staticfiles %}
    <link rel="stylesheet", href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="type/css" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{employee.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Contact:</label>
    <div class="col-sm-4">
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

employee/templates/employee/base.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% load staticfiles %}
    <link rel="stylesheet", href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="type/css" href="{% static 'css/style.css' %}"/>
</head>
<body>

</body>
</html>

employee/templates/show.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Records</title>
 {% load staticfiles %}
    <link rel="stylesheet", href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="type/css" href="{% static 'css/style.css' %}"/>

</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Employee ID</th>
        <th>Employee Name</th>
        <th>Employee Email</th>
        <th>Employee Contact</th>
        <th>Employee Gender</th>
        <th>Employee Country</th>
        <th>Employee State</th>
        <th>Employee Language</th>
        <th>Employee Image</th>

        <th>Actions</th>
    </tr>
    </thead>
    <body>
    {% for employee in employee %}
                <tr>
                    <td>{{ employee.eid }}</td>
                    <td>{{ employee.ename }}</td>
                    <td>{{ employee.eemail }}</td>
                    <td>{{ employee.econtact }}</td>
                    <!--<td>{{ employee.gender }}</td>-->
                    <td>{{ employee.ecountry }}</td>
                    <td>{{ employee.estate }}</td>
                    <td>{{ employee.elanguage }}</td>

                    <td>{{ employee.eimage }}</td>

                    <td>
                        <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
                        <a href="/delete/{{ employee.id }}">Delete</a>
                    </td>
                </tr>
    {% endfor %}
    </body>
</table>
<br>
<br>
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
</body>
</html>